In [64]:
#!pip install geopy
from geopy.geocoders import Nominatim
import pandas as pd

# load the data
df = pd.read_csv("C:\\Users\\User\\Downloads\\Eggoz\\NCR Retailers2.csv")
df.head()

,retailer_name,onboarding_date,onboarding_status,area_classification,zone_name,city_name,latitude,longitude
0,G1538* agarwal store,2020-10-08 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.459000,77.044000
1,G1380* Ankit vita dairy (sector - 28),2020-07-30 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.463753,77.083876
2,G1360* ashyan enterprises (chill),2020-09-18 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.422000,77.090000
3,G1402* Balaji General Store Vakil Market,2020-08-23 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.473670,77.080120
4,G1346* balnath store 56,2020-10-28 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.430000,77.103000

In [65]:
df = df.dropna()

In [24]:
# Initialize geolocator
geolocator = Nominatim(user_agent="API key 1")

# Function to reverse geocode coordinates
def reverse_geocode(row):
    location = geolocator.reverse(f"{row['latitude']},{row['longitude']}")
    address = location.raw['address']
    return address.get('city','') if address else None

In [46]:
import pandas as pd
from geopy.geocoders import Bing

API_KEY = "AtEi89PbWUDFGvod4dsiaJPS0bRXlcYPefyXL7Csq0K_EF7v6QHpfZYi5UIAq-Ys"  # Replace with your Bing Maps API key
geolocator = Bing(API_KEY, user_agent="Location finder")

# Assuming df is your DataFrame with 'Latitude' and 'Longitude' columns


def coordinates_to_address(latitude, longitude):
    location = geolocator.reverse((latitude, longitude))
    if location and hasattr(location, 'address'):
        return location.address
    else:
        return None

# Apply the function to create a new 'Address' column
df['Address'] = df.apply(lambda row: coordinates_to_address(row['latitude'], row['longitude']), axis=1)

# Extract city from the address and create a new 'City' column
df['City'] = df['Address'].apply(lambda x: x.split(', ')[-3] if x else None)

# Display the modified DataFrame
print(df['City'])

0       HR 122001
1       HR 122009
2       HR 122011
3       HR 122009
4       HR 122011
          ...
2681    DL 110011
2682    HR 122505
2683    HR 122003
2684    HR 122003
2685    HR 122003
Name: City, Length: 2224, dtype: object

In [69]:
# Extract city from the address and create a new 'City' column
df['City'] = df['Address'].apply(lambda x: x.split(',')[-3] if x else None)

# Display the modified DataFrame
print(df['City'])

IndexError: list index out of range

In [67]:
df = pd.read_csv("C:\\Users\\User\\Downloads\\Eggoz\\final_df.csv")

In [55]:
df_new

,retailer_name,onboarding_date,onboarding_status,area_classification,zone_name,city_name,latitude,longitude,Address,City,City Name
0,G1538* agarwal store,2020-10-08 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.459000,77.044000,"1002, Gurugram, HR 122001, India",HR 122001,Gurugram
1,G1380* Ankit vita dairy (sector - 28),2020-07-30 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.463753,77.083876,"5507, Gurugram, HR 122009, India",HR 122009,Gurugram
2,G1360* ashyan enterprises (chill),2020-09-18 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.422000,77.090000,"27-T, Sohna, HR 122011, India",HR 122011,Sohna
3,G1402* Balaji General Store Vakil Market,2020-08-23 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.473670,77.080120,"1485, Gurugram, HR 122009, India",HR 122009,Gurugram
4,G1346* balnath store 56,2020-10-28 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.430000,77.103000,"Tower C 301 Alaknanda, Golf Course Road, Gurug...",HR 122011,Golf Course Road
...,...,...,...,...,...,...,...,...,...,...,...
2219,G3221* Ichibanya India Pvt. Ltd M3M,2023-12-24 13:30:31.728347,Active,NCR-UB,NCR,Gurgaon,28.609741,77.204685,"2, Dara Shikoh Road, New Delhi, DL 110011, India",DL 110011,Dara Shikoh Road
2220,G3222* GGN-Sector 37,2023-12-26 04:45:07.959518,Active,NCR-ON-MT,NCR,Gurgaon,28.377869,76.975816,"Delhi Ajmer Expressway, Manesar, HR 122505, India",HR 122505,Manesar
2221,N5009* NOD- Sector 117 network,2023-12-26 05:27:38.390930,Active,NCR-ON-MT,NCR,Noida,28.446077,77.043567,"411, Gurugram, HR 122003, India",HR 122003,Gurugram
2222,D4971* PJTJ Mundka Coldstar,2023-12-27 05:38:03.301488,Active,NCR-ON-MT,NCR,Delhi,28.446083,77.043577,"411, Gurugram, HR 122003, India",HR 122003,Gurugram
2223,G3223* PJTJ GGN TCI,2023-12-27 05:46:17.785628,Active,NCR-ON-MT,NCR,Gurgaon,28.434730,77.044921,"372, Gurugram, HR 122003, India",HR 122003,Gurugram

In [56]:
df_new["city_name"].unique()

array(['Gurgaon', 'Delhi', 'Faridabad', 'Noida', 'Ghaziabad',
       'Chandigarh', 'Jaipur', 'Panchkula', 'Mohali', 'Ludhiana'],
      dtype=object)

In [30]:
df_new["area_classification"].unique()

array(['Gurgaon-GT', 'Delhi-GT', 'NCR-OF-MT', 'Noida-GT', 'NCR-ON-MT',
       'NCR-UB', 'NCR-HORECA'], dtype=object)

In [57]:
df_new

,retailer_name,onboarding_date,onboarding_status,area_classification,zone_name,city_name,latitude,longitude,Address,City,City Name
0,G1538* agarwal store,2020-10-08 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.459000,77.044000,"1002, Gurugram, HR 122001, India",HR 122001,Gurugram
1,G1380* Ankit vita dairy (sector - 28),2020-07-30 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.463753,77.083876,"5507, Gurugram, HR 122009, India",HR 122009,Gurugram
2,G1360* ashyan enterprises (chill),2020-09-18 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.422000,77.090000,"27-T, Sohna, HR 122011, India",HR 122011,Sohna
3,G1402* Balaji General Store Vakil Market,2020-08-23 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.473670,77.080120,"1485, Gurugram, HR 122009, India",HR 122009,Gurugram
4,G1346* balnath store 56,2020-10-28 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.430000,77.103000,"Tower C 301 Alaknanda, Golf Course Road, Gurug...",HR 122011,Golf Course Road
...,...,...,...,...,...,...,...,...,...,...,...
2219,G3221* Ichibanya India Pvt. Ltd M3M,2023-12-24 13:30:31.728347,Active,NCR-UB,NCR,Gurgaon,28.609741,77.204685,"2, Dara Shikoh Road, New Delhi, DL 110011, India",DL 110011,Dara Shikoh Road
2220,G3222* GGN-Sector 37,2023-12-26 04:45:07.959518,Active,NCR-ON-MT,NCR,Gurgaon,28.377869,76.975816,"Delhi Ajmer Expressway, Manesar, HR 122505, India",HR 122505,Manesar
2221,N5009* NOD- Sector 117 network,2023-12-26 05:27:38.390930,Active,NCR-ON-MT,NCR,Noida,28.446077,77.043567,"411, Gurugram, HR 122003, India",HR 122003,Gurugram
2222,D4971* PJTJ Mundka Coldstar,2023-12-27 05:38:03.301488,Active,NCR-ON-MT,NCR,Delhi,28.446083,77.043577,"411, Gurugram, HR 122003, India",HR 122003,Gurugram
2223,G3223* PJTJ GGN TCI,2023-12-27 05:46:17.785628,Active,NCR-ON-MT,NCR,Gurgaon,28.434730,77.044921,"372, Gurugram, HR 122003, India",HR 122003,Gurugram

In [58]:
# Function to extract the third last word as city name
def extract_city(row):
    words = row['Address'].split(',')
    if len(words) >= 3:
        return words[-3]
    else:
        return 'NA'

# Apply the function to create the 'CityNames' column
df_new['City_Name'] = df_new.apply(extract_city, axis=1)

In [59]:
df_new.isna().sum()

retailer_name          0
onboarding_date        0
onboarding_status      0
area_classification    0
zone_name              0
city_name              0
latitude               0
longitude              0
Address                0
City                   0
City Name              0
City_Name              0
dtype: int64

In [60]:
df_new=df_new[['retailer_name', 'onboarding_date', 'onboarding_status',
       'area_classification', 'zone_name', 'city_name', 'latitude',
       'longitude', 'Address', 'City_Name']]

In [61]:
df_new

,retailer_name,onboarding_date,onboarding_status,area_classification,zone_name,city_name,latitude,longitude,Address,City_Name
0,G1538* agarwal store,2020-10-08 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.459000,77.044000,"1002, Gurugram, HR 122001, India",Gurugram
1,G1380* Ankit vita dairy (sector - 28),2020-07-30 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.463753,77.083876,"5507, Gurugram, HR 122009, India",Gurugram
2,G1360* ashyan enterprises (chill),2020-09-18 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.422000,77.090000,"27-T, Sohna, HR 122011, India",Sohna
3,G1402* Balaji General Store Vakil Market,2020-08-23 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.473670,77.080120,"1485, Gurugram, HR 122009, India",Gurugram
4,G1346* balnath store 56,2020-10-28 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.430000,77.103000,"Tower C 301 Alaknanda, Golf Course Road, Gurug...",Gurugram
...,...,...,...,...,...,...,...,...,...,...
2219,G3221* Ichibanya India Pvt. Ltd M3M,2023-12-24 13:30:31.728347,Active,NCR-UB,NCR,Gurgaon,28.609741,77.204685,"2, Dara Shikoh Road, New Delhi, DL 110011, India",New Delhi
2220,G3222* GGN-Sector 37,2023-12-26 04:45:07.959518,Active,NCR-ON-MT,NCR,Gurgaon,28.377869,76.975816,"Delhi Ajmer Expressway, Manesar, HR 122505, India",Manesar
2221,N5009* NOD- Sector 117 network,2023-12-26 05:27:38.390930,Active,NCR-ON-MT,NCR,Noida,28.446077,77.043567,"411, Gurugram, HR 122003, India",Gurugram
2222,D4971* PJTJ Mundka Coldstar,2023-12-27 05:38:03.301488,Active,NCR-ON-MT,NCR,Delhi,28.446083,77.043577,"411, Gurugram, HR 122003, India",Gurugram
2223,G3223* PJTJ GGN TCI,2023-12-27 05:46:17.785628,Active,NCR-ON-MT,NCR,Gurgaon,28.434730,77.044921,"372, Gurugram, HR 122003, India",Gurugram

In [63]:
df_new.to_csv("final_city_names.csv",index=False)

In [24]:
df_new["CityNames"].unique()

array(['Gurugram', 'Gurgaon', 'New Delhi', 'Faridabad', 'Noida',
       'Ghaziabad', 'Delhi', 'Chandigarh', 'Jaipur'], dtype=object)

In [70]:
df.head()

,retailer_name,onboarding_date,onboarding_status,area_classification,zone_name,city_name,latitude,longitude,Address,City,City Name
0,G1538* agarwal store,2020-10-08 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.459000,77.044000,"1002, Gurugram, HR 122001, India",HR 122001,Gurugram
1,G1380* Ankit vita dairy (sector - 28),2020-07-30 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.463753,77.083876,"5507, Gurugram, HR 122009, India",HR 122009,Gurugram
2,G1360* ashyan enterprises (chill),2020-09-18 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.422000,77.090000,"27-T, Sohna, HR 122011, India",HR 122011,Sohna
3,G1402* Balaji General Store Vakil Market,2020-08-23 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.473670,77.080120,"1485, Gurugram, HR 122009, India",HR 122009,Gurugram
4,G1346* balnath store 56,2020-10-28 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.430000,77.103000,"Tower C 301 Alaknanda, Golf Course Road, Gurug...",HR 122011,Golf Course Road

In [58]:
from geopy.geocoders import Bing

API_KEY = "AtEi89PbWUDFGvod4dsiaJPS0bRXlcYPefyXL7Csq0K_EF7v6QHpfZYi5UIAq-Ys"
geolocator = Bing(API_KEY, user_agent="Location finder")

def coordinates_to_address(latitude, longitude):
    location = geolocator.reverse((latitude, longitude))
    print(location)
    if location and hasattr(location, 'address'):
        return location.address
    else:
        return None
# Sample coordinates
latitude = 28.459000
longitude = -73.985428

# Call the coordinates_to_address function
address = coordinates_to_address(latitude, longitude)

# Extract city from the address
city = address.split(', ')[1] if address else None

# Display the result
print("City:", city)
print(address)

20 W 34th St, Midtown South, NY 10001, United States
City: Midtown South
20 W 34th St, Midtown South, NY 10001, United States

In [71]:
df=pd.read_csv("C:\\Users\\User\\Downloads\\Eggoz\\final_city_names.csv")

In [74]:
df['City Name 2'] = df['Address'].str.split(',').str[-3].str.strip()

In [75]:
df

,retailer_name,onboarding_date,onboarding_status,area_classification,zone_name,city_name,latitude,longitude,Address,City_Name,City Name,City Name 2
0,G1538* agarwal store,2020-10-08 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.459000,77.044000,"1002, Gurugram, HR 122001, India",Gurugram,Gurugram,Gurugram
1,G1380* Ankit vita dairy (sector - 28),2020-07-30 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.463753,77.083876,"5507, Gurugram, HR 122009, India",Gurugram,Gurugram,Gurugram
2,G1360* ashyan enterprises (chill),2020-09-18 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.422000,77.090000,"27-T, Sohna, HR 122011, India",Sohna,Sohna,Sohna
3,G1402* Balaji General Store Vakil Market,2020-08-23 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.473670,77.080120,"1485, Gurugram, HR 122009, India",Gurugram,Gurugram,Gurugram
4,G1346* balnath store 56,2020-10-28 18:30:00.000000,Active,Gurgaon-GT,NCR,Gurgaon,28.430000,77.103000,"Tower C 301 Alaknanda, Golf Course Road, Gurug...",Gurugram,Gurugram,Gurugram
...,...,...,...,...,...,...,...,...,...,...,...,...
2219,G3221* Ichibanya India Pvt. Ltd M3M,2023-12-24 13:30:31.728347,Active,NCR-UB,NCR,Gurgaon,28.609741,77.204685,"2, Dara Shikoh Road, New Delhi, DL 110011, India",New Delhi,New Delhi,New Delhi
2220,G3222* GGN-Sector 37,2023-12-26 04:45:07.959518,Active,NCR-ON-MT,NCR,Gurgaon,28.377869,76.975816,"Delhi Ajmer Expressway, Manesar, HR 122505, India",Manesar,Manesar,Manesar
2221,N5009* NOD- Sector 117 network,2023-12-26 05:27:38.390930,Active,NCR-ON-MT,NCR,Noida,28.446077,77.043567,"411, Gurugram, HR 122003, India",Gurugram,Gurugram,Gurugram
2222,D4971* PJTJ Mundka Coldstar,2023-12-27 05:38:03.301488,Active,NCR-ON-MT,NCR,Delhi,28.446083,77.043577,"411, Gurugram, HR 122003, India",Gurugram,Gurugram,Gurugram
2223,G3223* PJTJ GGN TCI,2023-12-27 05:46:17.785628,Active,NCR-ON-MT,NCR,Gurgaon,28.434730,77.044921,"372, Gurugram, HR 122003, India",Gurugram,Gurugram,Gurugram

In [52]:
df.to_csv("final_df.csv",index=False)

In [20]:
# Display the DataFrame with the new 'Location' column
df.head()
df.shape

GeocoderInsufficientPrivileges: Non-successful status code 403